### PR TITLE
Add Tailwind v3 extended color palette for all valid utilities

### PR DESCRIPTION
**Pull request by NoaVidovic**
The repository was missing many default colors that were added in Tailwind v3, such as cyan or orange. This pull request simply adds the missing colors.

It is important to note that Tailwind changed the default value of green, purple and yellow colors (these were renamed to emerald, violet and amber respectively, and the old names were repurposed for other color values) - details available [here](https://github.com/tailwindlabs/tailwindcss/pull/5384). Therefore, any code that uses this package should be modified to reflect this change. **This may be considered a breaking change.**

Also, I do not have a utility to automatically sort the functions alphabetically, as is the case in the base repository, so the ordering is sort of all out of whack. Feel free to modify this when merging.

### CODE REVIEW

**Comment by matheus23** [comment]
Thank you for doing this! I really appreciate it.

Unfortuantely, the elm-default-tailwind-modules package is already close to its size limits for package.elm-lang.org uploads.
I'm postponing this change until #6 is done.
Once we have #6, I'll re-generate this repo's code with the new abstracted-out colors (see https://github.com/matheus23/elm-tailwind-modules/pull/16) and the generated files will be *much* smaller, while still making all color/utility combinations possible.

**Comment by matheus23** [comment]
@NoaVidovic I've uploaded a new version, let me know if that works for you: https://github.com/matheus23/elm-default-tailwind-modules/issues/6#issuecomment-1418165700

**Comment by NoaVidovic** [comment]
Thank you so much for the work you put in here! However, I do not see version 3.0.0 on the elm packages website - it still shows 2.0.3 as the latest and there is no bg_color function nor anything else.

**Comment by matheus23** [comment]
@NoaVidovic Hmm it's there for me: https://package.elm-lang.org/packages/matheus23/elm-default-tailwind-modules/latest/Tailwind-Utilities#bg_color

**Comment by matheus23** [comment]
You can see the published versions here: https://package.elm-lang.org/packages/matheus23/elm-default-tailwind-modules/

**Comment by NoaVidovic** [comment]
Yeah, it's not showing up for me:
screenshot

**Comment by matheus23** [comment]
Wow :D

you must be hitting some kind of cashing issue. For me it's there:
image

**Comment by matheus23** [comment]
What happens if you try this link? https://package.elm-lang.org/packages/matheus23/elm-default-tailwind-modules/3.0.0/Tailwind-Utilities#bg_color

**Comment by NoaVidovic** [comment]
So, confusingly, while clearing the cache fixed the issue and I can now see version 3.0.0 (and functions such as bg_color and text_color show up), the Tailwind.Theme module doesn't show up (as shown in the attached image)

Updating my elm.json does download the Tailwind.Theme module as it should, but elm make doesn't recognize it when compiling...

image

**Comment by matheus23** [comment]
That one is my bad!
I've published version 3.1.0 to fix this issue:
image

**Comment by NoaVidovic** [comment]
Works like a charm now! Thanks a lot!

**Pull request closed without merging**
