### PR TITLE
Upgrade elm-css version to 18.0.0

### PR DESCRIPTION
**Pull request by petteraas**

### CODE REVIEW

**Comment by matheus23** [comment]
Hi @petteraas. Thank you for this PR :)
The way I understand the version bounds in the current release is they should allow both versions 17.0.1 as well as 18.0.0, isn't that correct?
The version bounds were intentionally lax so that downstream users wouldn't have to upgrade immediately, but they could still use it with version 18.0.0 if they wanted to. Perhaps that didn't work as I expected?

**Comment by petteraas** [comment]
Hi @matheus23 I was unable to upgrade elm-css in a project because of the current version limitation in elm-default-tailwind-modules, I think it's caused by the use of  ` .... < 18.0.0 ` which seems to include everything `lesser than 18.0.0` and not ` lesser than or equal to` , could probably have tried ` 17.0.1 <= v <= 18.0.0 ` if you prefer that?

**Comment by matheus23** [comment]
Ah. my bad. I thought the bound was set at `17.0.1 <= v < 19.0.0`.
Let me see if that works, otherwise I'll just merge this :)

**Comment by matheus23** [comment]
The version bound should now be `< 19.0.0`. LMK if that works on your end. The new published version is 4.0.1

**Comment by petteraas** [comment]
Yes, it seems to work with version 4.0.1,  now `elm-json upgrade --unsafe` suggests a upgrade of elm-css to 18.0.0 , so I guess this pull request can be closed.

**Comment by matheus23** [comment]
Thanks for raising this issue & being proactive in solving it (again) :)

**Pull request closed without merging**
